version: 2
updates:
  - package-ecosystem: gomod
    directory: "/pb_backend"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/pb_frontend"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/pb_backend"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/pb_frontend"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
