global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'pixelbattle-gateway'
    static_configs:
      - targets: ['tasks.gateway-1:8080', 'tasks.gateway-2:8080']
        labels:
          version: candidate
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis-exporter'
    static_configs:
      - targets:
          - 'tasks.redis-exporter-c1:9121'
          - 'tasks.redis-exporter-c2:9121'
          - 'tasks.redis-exporter-c3:9121'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: A
        port: 9100
    scrape_interval: 10s

  - job_name: 'caddy'
    static_configs:
      - targets: ['tasks.caddy:2019']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://tasks.caddy/healthz
          - http://tasks.caddy/init_canvas
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tasks.blackbox-exporter:9115

  - job_name: 'blackbox-ws-handshake'
    metrics_path: /probe
    params:
      module: [ws_handshake]
    static_configs:
      - targets:
          - tasks.caddy:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tasks.blackbox-exporter:9115
