apiVersion: 1

datasources:
  - name: Infinity
    uid: infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://backend:8080
    editable: true
    jsonData:
      tlsSkipVerify: true
